/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMaestroAdviceRouteImport } from './routes/api.maestro-advice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaestroAdviceRoute = ApiMaestroAdviceRouteImport.update({
  id: '/api/maestro-advice',
  path: '/api/maestro-advice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/maestro-advice': typeof ApiMaestroAdviceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/maestro-advice': typeof ApiMaestroAdviceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/maestro-advice': typeof ApiMaestroAdviceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/maestro-advice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/maestro-advice'
  id: '__root__' | '/' | '/api/maestro-advice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMaestroAdviceRoute: typeof ApiMaestroAdviceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maestro-advice': {
      id: '/api/maestro-advice'
      path: '/api/maestro-advice'
      fullPath: '/api/maestro-advice'
      preLoaderRoute: typeof ApiMaestroAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMaestroAdviceRoute: ApiMaestroAdviceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
